### ISSUE TITLE
Adding custom API URL

### ISSUE THREAD

**Issue by F2VILLE** [simonla/obsidian_waka_box#1]
Hey, what's up ?
I edited your code to add custom Wakapi URL (for self hosted servers). As I am not really confident about how I edited your code, I don't want to make a pull request, but it would be nice if you could check it and add it on the extension. 
I used the template of your repo, I think you can look at it on my profile.
If you want to chat about it, my discord is **[f2ville](https://discord.com/users/836685191812218970)**

Have a nice day / evening !

**Comment by simonla** [comment]
Could you please direct me to the documentation for the self-hosted WakaTime API?

**Comment by F2VILLE** [comment]
Sure : https://wakapi.dev/swagger-ui/swagger-ui/index.html

If you want my edition seems to work, for the baseURL I did like this :

```js
const baseUrl = (apiURL.endsWith("/") ? apiURL.slice(0, -1) : apiURL) + (apiURL.includes("wakatime.com") ? "/users/current/summaries" : "/compat/wakatime/v1/users/current/summaries")
```

So basically from what I found the endpoint to get summaries from wakapi self-hosted server is `/compat/wakatime/v1/users/current/summaries`

**Comment by Wanxp** [comment]
I has pushed a "Pull Request" #2  to support this function:
![1694880172041](https://github.com/simonla/obsidian_waka_box/assets/26840810/46763e3a-3140-470b-a61f-4ab4b1c29652)
.
Wait @simonla accept this request.
If you could not wait for this, please contact me.

**Comment by simonla** [comment]
Waiting for obsidian review update
