### ISSUE TITLE
extension overwrote content

### ISSUE THREAD

**Issue by vogler** [simonla/obsidian_waka_box#6]
I installed the extension yesterday, but it somehow deleted all my content for the daily note I had below the box in a list:
![image](https://github.com/simonla/obsidian_waka_box/assets/493741/b8dd9f46-7b59-4e60-a76a-1744a5486ff5)

**Comment by simonla** [comment]
This plugin will replace code block by follow regex:

https://github.com/simonla/obsidian_waka_box/blob/3b2bb0ac228c78f900fc36aa26263a02611d9daa/src/main.ts#L144
